name: CI
on: [push, pull_request]
jobs:
  build:
    strategy:
      matrix:
        platform: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "12.x"
      - name: Set up git repo
        uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          npm -v
          npm ci
      - name: Build artifacts
        run: |
          npm -v
          npm run build
